### ISSUE TITLE
Phi-3 cannot be exported to iree-turbine

### ISSUE THREAD

**Issue by maxbartel** [iree-org/iree-turbine#12]
Hi!

Importing Phi 3 into turbine does not seem to be possible at the moment. 

Minimal reproducer:

```python
from transformers import AutoTokenizer, AutoModelForCausalLM
from iree.turbine import aot

tokenizer = AutoTokenizer.from_pretrained(
    "microsoft/Phi-3-mini-128k-instruct", trust_remote_code=True
)
model = AutoModelForCausalLM.from_pretrained(
    "microsoft/Phi-3-mini-128k-instruct",
    trust_remote_code=True,
)


input_token = tokenizer.apply_chat_template(
    [{"role": "user", "content": "This is a test promt"}],
    add_generation_prompt=True,
    return_tensors="pt",
)

inst = aot.export(model, input_token)

```

The error is 
`torch._dynamo.exc.Unsupported: call_method UserDefinedObjectVariable(Logger) warning_once [ConstantVariable()] {}`

I tried different ways of using the api to export the model, but was not successful. This version does not even use dynamic shapes. If I am doing something wrong, please tell me!

Thank you for the help!

**Comment by stellaraccident** [comment]
Full call stacks are needed to do any routing. From what I can see of the error message, this is a torch bug and can also be reprod with torch.export.export

**Comment by maxbartel** [comment]
Here is the complete output https://gist.github.com/maxbartel/343d35be7fa22df76007e2e54726b4fe

Sorry, should have included it earlier.

**Comment by maxbartel** [comment]
I opened https://github.com/iree-org/iree-turbine/pull/14 to fix this. 

The model will still not work however. There are some branching statements depending on data values. This is not supported in torch.export. There is even a whole Google Docs sheet about this https://docs.google.com/document/d/1HSuTTVvYH1pTew89Rtpeu84Ht3nQEFTYhAX3Ypa_xJs/edit#heading=h.r02234kuof4f

I opened https://huggingface.co/microsoft/Phi-3-mini-128k-instruct/discussions/61 on the model itself, but I don't have much hope...
