### ISSUE TITLE
October 2024 Tkw Release Notes

### ISSUE THREAD

**Issue by harsh-nod** [iree-org/iree-turbine#120]
This issue lists all feature requests and improvements slated for the Oct 2024 Tkw release.

- [ ] Flash Attention Implementation
- [ ] Flash Attention Performance Improvements
- [x] Implicit GEMM Implementation
- [x] Implicit GEMM Performance Improvements
- [x] Unaligned WG/elements_per_thread size handling (masking)
- [x] Modulo Scheduling Implementation
- [x] GEMM Instruction Scheduling
- [ ] Performance Dashboard
- [ ] Auto-tuning Capability
- [ ] Batch GEMM support
- [ ] Dynamic shapes for GEMMs
- [ ] Unaligned shapes for GEMMs
- [ ] GEMM with fused elementwise operations

**Comment by Hardcode84** [comment]
* unaligned WG/elements_per_thread size handling (masking)

**Comment by harsh-nod** [comment]
Sprint complete.
