### ISSUE TITLE
Install error when I try to install iree-turbine in my local environment?

### ISSUE THREAD

**Issue by FlintWangacc** [iree-org/iree-turbine#37]
When I try to install ```iree-turbine``` in my local environment, it report error in this progress.

```shell
xxxx@PC:~/iree-turbine$ sudo python3 setup.py install
.......
Installed /usr/local/lib/python3.10/dist-packages/shark_turbine-2.3.0rc20240410-py3.10.egg
Processing dependencies for shark-turbine==2.3.0rc20240410
Searching for torch>=2.3.0
Reading https://pypi.org/simple/torch/
Downloading https://files.pythonhosted.org/packages/cb/e2/1bd899d3eb60c6495cf5d0d2885edacac08bde7a1407eadeb2ab36eca3c7/torch-2.3.1-cp310-cp310-manylinux1_x86_64.whl#sha256=605a25b23944be5ab7c3467e843580e1d888b8066e5aaf17ff7bf9cc30001cc3
error: The read operation timed out 
```

I was trying to investigate the progress that iree-turbine change a neural network into the MLIR representation.

**Comment by stellaraccident** [comment]
This is failing on a network issue when trying to install torch. I recommend trying to install torch manually and figuring out why this is causing trouble for you. 

Also, I highly recommend not doing "sudo pip install" if you are in an environment you care about.
