### ISSUE TITLE
Tkw Outstanding Issues (8/13/24)

### ISSUE THREAD

**Issue by harsh-amd** [iree-org/iree-turbine#79]
Week of 08/12 - 08/17:
- [x] (Ivan) Finish mapping & run transpose end to end (stretch goal)
- [x] (Harsh) Finish index PR, promotion to shared memory PR (codegen stretch-goal) and minimizing global loads PR. FA3 IR (get through the expansion), ML model training on schedules, share thoughts on initial prototype
- [x] (Stan) Matmul end to end, FA end to end

List of outstanding issues:

* Functionality
- [x] MMA lowering
- [x] Promotion to shared memory
- [x] Read/Transpose/Write kernels (global memory)
- [x] Barrier Placement

* Performance
- [x] Minimizing the number of global loads
- [ ] Shared memory bank conflicts (padding)
- [x] Software Pipelining (Algorithm)
- [ ] Software Pipelining (Construction of the prologue, kernel and epilogue)

**Comment by harsh-nod** [comment]
Closing this out for a monthly release cadence.
